conftest.py

https://github.com/astropy/package-template/issues/40

fix in conftest.py from:

---

pyspeckit/cubes/SpectralCube.py

cc @dinossimpson this is an example of a cleanup (in response to more queries from the same user)

add a more helpful error message when the loaded cube shape is wrong

---

pyspeckit/wrappers/fitnh3.py

So far not added to the plotter, though.

Add higher-j NH3 lines to the wrapper

---

examples/fit_nh3_cube.py
examples/h2co_mm_example.py
examples/hcn_example.py
examples/n2hp_cube_example.py
examples/reduce_class.py

follow up of #26
@dinossimpson review?

replace units with unit in tests/examples

---

pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/models/model.py

* try to catch bad keyword passing from __call__ to multifit
* try to catch invalid parameter values passed to emcee

BUGFIX: keyword passing & parameter checking

---

pyspeckit/spectrum/units.py

Fixes nested SpectroscopicAxis in `__repr`__

fix in SpectroscopicAxis.__repr__

---

pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/models/ammonia_constants.py
pyspeckit/spectrum/models/hyperfine.py
pyspeckit/spectrum/models/model.py

Fix for Issue 46 continued: more careful checks

---

pyspeckit/cubes/SpectralCube.py
pyspeckit/spectrum/plotters.py
pyspeckit/spectrum/units.py
pyspeckit/spectrum/writers/fits_writer.py

See commit message for details

Fix a bug in spectroscopicaxis repr and getitem

---

pyspeckit/cubes/SpectralCube.py
pyspeckit/spectrum/plotters.py
pyspeckit/spectrum/units.py
pyspeckit/spectrum/writers/fits_writer.py

convert_to_unit was doing nothing.  This is a fix for that issue.
TODO (@dinossimpson): regression test!

BUGFIX: convert_to_unit

---

pyspeckit/cubes/SpectralCube.py

See https://github.com/pyspeckit/pyspeckit/issues/68 for details
-Number reported in "Final fit" message is right
-When using a single core (multicore=1) the progress message is right
-Changed default value of momenteach and fiteach to multicore=1
-Multicore processing is done only when multicore>1
-Progress message in multicore processing is not right... but better

SpectralCube.fiteach: Broken percentage progress

---

pyspeckit/cubes/SpectralCube.py
pyspeckit/mpfit/mpfit.py
pyspeckit/spectrum/baseline.py
pyspeckit/spectrum/classes.py
pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/interactive.py
pyspeckit/spectrum/models/model.py

The 'multifit' approach was broken in a recent commit + pull request because
parinfo was being constructed without proper information about `npeaks`.
TODO:

BUGFIX: can only fit a single peak right now

---

pyspeckit/spectrum/plotters.py

Offset coordinates are annoying:
the absolute coordinates are nicer:
workardound:
`sp.plotter.axis.ticklabel_format(useOffset=False)`
cc @mikelum

Display absolute coordinates instead of offset coordinates

---

pyspeckit/cubes/SpectralCube.py
pyspeckit/cubes/mapplot.py
pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/models/model.py
pyspeckit/spectrum/parinfo.py
pyspeckit/spectrum/readers/txt_reader.py

pyspeckit was annoyingly slow to import.  It turns out this is due to some slow submodules that could be readily sped up

Improve import speed

---

pyspeckit/spectrum/models/n2dp.py

I created an N2D+ models that handles the 2-1 and 3-2 lines. It should be fine, except that I don't know what to put for `relative_strength_total_degeneracy`, right now they are all set to 1.
If these modifications are OK I will create models for NH2D, now that I think I learned how to setup the models.

New N2D+ model

---

pyspeckit/spectrum/fitters.py

Replace outdated 'sp.' reference with 'self.Spectrum.' to fix the 'fitted' option for EQW call.
Also display the EQW fit 'rectangle' at the centroid of the fitted Gaussian which is closest to the center of the passed window.

Fixes fitted option of EQW. Displays fit at the center of passed window.

---

pyspeckit/cubes/cubes.py

I'm doing this slowly over many commits...

Small refactor toward py3 compatibility

---

.travis.yml

Fix travis conda location

---

pyspeckit/spectrum/models/model.py
pyspeckit/spectrum/tests/test_fitter.py

python3 does not have an 'exec' capability any more, even though the exec
function still exists - it just doens't do anything.
This definitely requires a test!  Don't merge it until you have one!!!!

Fix a bug related to setting parameters in python3

---

pyspeckit/__init__.py

see http://stackoverflow.com/questions/35364810/importerror-no-module-named-version-in-astropy

Minor: don't import version

---

pyspeckit/cubes/tests/test_cubetools.py

As per https://github.com/astropy/astropy/issues/4648

Updated header creation from a dictionary

---

CHANGES.rst
pyspeckit/cubes/SpectralCube.py
pyspeckit/spectrum/classes.py
pyspeckit/spectrum/readers/fits_reader.py
pyspeckit/spectrum/readers/tests/test_specutils_reading.py

It's been sitting there with a `NotImplementedError` forever, but now that I
understand how to use specutils again, it's sensible to have it in place.

Implement from_spectrum1d

---

.travis.yml
pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/interactive.py
pyspeckit/spectrum/plotters.py
pyspeckit/spectrum/tests/test_units.py

Support for the glue plugin (https://github.com/glue-viz/glue-pyspeckit-plugin)

Glue-viz plugin

---

pyspeckit/spectrum/plotters.py

Allow NaNs to be used as flags

---

docs/example_minimal_cube
docs/examples.rst
examples/cube_minimal_example.py

Addresses #157. Actually, with #161 the example can be made even shorter, but I am not sure if such a recent change should be included.
Also, I have no idea if I put everything needed in place for the docs to compile properly, please double-check on that.

a simple mini cube fitting example

---

pyspeckit/cubes/SpectralCube.py

fix a typo in fiteach for start_from_point='center'

---

examples/n2hp_cube_example.py
pyspeckit/mpfit/mpfit.py
pyspeckit/spectrum/baseline.py

Specifically, https://github.com/numpy/numpy/blob/master/doc/release/1.11.0-notes.rst#assigning-to-slicesviews-of-maskedarray

Handle numpy masked array API change

---

README.rst

I noticed the Zenodo badge on the readme seems to be broken, and this should fix it

Fix Zenodo badge

---

pyspeckit/spectrum/readers/read_class.py

These changes work for reading SMT and APEX CLASS v1 data for me and should not break anything. It may be necessary to make more modifications for different file versions but I am not sure...

Class reader python 3 compatibility

---

pyspeckit/cubes/SpectralCube.py
pyspeckit/cubes/tests/test_cubetools.py

```python
In [4]: id(spc.cube)
Out[4]: 4668431936
In [5]: id(spc.copy().cube)
Out[5]: 4668431936
```

Cube.copy() didn't copy the cube attribute

---

pyspeckit/spectrum/models/lte_molecule.py
pyspeckit/spectrum/readers/read_class.py

I still can't read CLASS files in python3, and it has something to do with the encoding.  I don't fully understand it yet, as debugging is fairly challenging.  I run into filesize exceptions, which implies that I'm trying to read too many/few bits at certain points along the way.
This will be an update to https://github.com/pyspeckit/pyspeckit/pull/189. 
cc @migueldvb - have you had success reading CLASS files?  I've specifically been trying to read V1 files from APEX and they've been crashing.  If you have any more ideas, I'm open to them

Python 3 CLASS reader updates & fixes

---

pyspeckit/spectrum/models/ammonia.py

Filling fraction should be multiplying the spectrum, not the optical depth profile.

Fix filling fraction definition

---

pyspeckit/cubes/mapplot.py

Cube.mapplot() fix when window is closed

---

ah_bootstrap.py
docs/conf.py

@keflavich - Do you want me to put this package on the list to open automated helpers update PRs whenever a new release is out? If you have any more such packages please let me know.

Update astropy-helpers to v1.3

---

pyspeckit/spectrum/baseline.py
pyspeckit/spectrum/classes.py
pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/interactive.py
pyspeckit/spectrum/models/hill5infall.py
pyspeckit/spectrum/plotters.py

Add a series of small fixes

---

pyspeckit/cubes/SpectralCube.py
pyspeckit/cubes/tests/test_spectralcube.py

Fix issue #218

---

pyspeckit/spectrum/models/model.py
pyspeckit/spectrum/tests/test_fitter.py

Passing `use_lmfit` to `specfit` results in the fitter returning parinfo that was generated on the guesses instead of fitted parameters. Steps to reproduce, adapted from the [spectrum from scratch example](http://pyspeckit.readthedocs.io/en/latest/example_fromscratch.html):
```python
import numpy as np
xaxis = np.linspace(-50, 150, 100.)
sigma = 10. 
center = 50. 
synth_data = np.exp(-(xaxis - center)**2 / (sigma**2 * 2.))
stddev = 0.1 
noise = np.random.randn(xaxis.size) * stddev
error = stddev * np.ones_like(synth_data)
data = noise + synth_data
sp_mpfit = pyspeckit.Spectrum(
data=data,
error=error,
xarr=xaxis,
xarrkwargs={'unit': 'km/s'},
unit='erg/s/cm^2/AA')
sp_lmfit = sp_mpfit.copy()
moment_guess = sp_mpfit.moments(vheight=False)
sp_mpfit.specfit(fittype='gaussian', …
```

Fix for lmfitter parameters

---

pyspeckit/cubes/SpectralCube.py

there were some indices that could potentially be floats when they shouldn't

Possible fix to #226: force more indices to ints

---

docs/example_hcop.py
docs/example_hcop.rst
docs/install_via_GitHub.rst
docs/projects.rst

There was some out-of-date, invalid code in the docs.
I really need to refactor and get doctests running =(

Fix HCOp example

---

pyspeckit/cubes/SpectralCube.py
pyspeckit/spectrum/models/model.py
pyspeckit/wrappers/fitnh3.py

Important for some GAS plotting stuff

Update the NH3 fit wrapper

---

.travis.yml
pyspeckit/cubes/mapplot.py
pyspeckit/spectrum/classes.py
pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/readers/tests/test_specutils_reading.py
pyspeckit/wrappers/fitnh3.py

First noted bug is that combining spectra with km/s units doesn't check if they
are in the same frame.

Attempt to fix some bugs in fitnh3_wrapper

---

pyspeckit/spectrum/fitters.py

This makes the DOF calculation a property, making it easier to maintain, and
corrects an error in the DOF calculation when parameters are tied.

Make DOF calculation a property

---

examples/ammonia_fit_example.py
pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/models/ammonia.py

Keywords were not being passed correctly, and the 'components' returned from the _ammonia_spectrum function were all the same array.

Fix ammonia hyperfine plotting

---

pyspeckit/spectrum/readers/read_class.py

Make CLASS reading work with fitted data

---

INSTALL.txt
docs/install.rst
docs/install_via_GitHub.rst

The installation docs were outdated, using bitbucket links, and read as though someone else had written them

Update installation docs

---

examples/synthetic_spectrum_example_witherrorestimates.py

This is an example to add to the paper.  It uses one of the existing examples from the docs and shows how good/bad the automated parameter error estimation is.

Added a new example

---

pyspeckit/spectrum/fitters.py
pyspeckit/spectrum/interactive.py
pyspeckit/spectrum/models/ammonia.py
pyspeckit/spectrum/models/hill5infall.py
pyspeckit/spectrum/models/hyperfine.py
pyspeckit/spectrum/models/inherited_voigtfitter.py
pyspeckit/spectrum/models/model.py
pyspeckit/spectrum/models/tests/test_ammonia.py
pyspeckit/spectrum/models/tests/test_hill5.py

cc @jdhenshaw 
For models like hyperfines and other physical models, we would like to be able to input guesses interactively.  However, since they have 4+ parameters, we need a way to translate "amplitude" into tex, tau, and other parameters.  The default should probably be tex=peak amplitude, tau=1.
A good implementation approach might be to add a `parse_3par_guesses` attribute to each model.

Interactive guessing for >3 component models

---

docs/index.rst
pyspeckit/spectrum/models/lte_molecule.py

Need to PR these to see if they fail

More documentation changes

---

pyspeckit/spectrum/models/ammonia_hf.py

Address an issue noted in #265, specifically https://github.com/pyspeckit/pyspeckit/issues/265#issuecomment-374007393.

NH3 optical depth normalization

---

.travis.yml
pyspeckit/spectrum/interactive.py
pyspeckit/spectrum/plotters.py

This is an attempt to fix #286

Fix 286: added tests and mpl3 compatibility change

---

pyspeckit/_astropy_init.py

This is an automated update made by the astropy package-template ``batchpr``
tool :robot: - feel free to close if it doesn't look good!
You can report issues to @bsipocz.

Package-template update: _astropy_init.py

---

.travis.yml
docs/plotting.rst
pyspeckit/conftest.py
setup.cfg

This is a small change, but pushing it to my master seemed to trigger some travis-ci failures, so I want to see what happens in the PR CI.

Add a link to Jeff's example

---

docs/fitting.rst

cc @jpinedaf @vlas-sokolov @jakeown @mcyc

Added links to multi-component fitting tools

---

pyspeckit/spectrum/fitters.py

Partial solution/workaround for #309 and another issue I started experiencing with legends in non-interactive backends

Improve legend robustness

---

CHANGES.rst
docs/classfiles.rst
docs/conf.py
docs/example_nh3.rst
docs/example_pymc.rst
docs/example_sn.rst
docs/faq.rst
docs/index.rst
docs/install.rst
docs/interactive.rst
docs/parameters.rst

Using [sphinx-astropy](https://github.com/astropy/sphinx-astropy) and some minor edits.

Switch to sphinx-astropy for sphinx configuration

---

pyspeckit/spectrum/models/n2dp.py

The file n2hp.py has been modified due to the extension of the model’s ability. Added new transition 1- 0.

Adding N2D+(1-0)

---

pyspeckit/spectrum/models/n2hp.py

-Added N2H+ (2-1) and (3-2)
-Frequencies and weights updated based on Dore (priv comm) and Pagani et al. (2009).
-A little bit of a clean-up in the N2H+ file.
This should address #279

Updated N2H+ model

---

pyspeckit/spectrum/models/n2hp.py

-The relative_strength_total_degeneracy did not store the J=1-0 transition, since I forgot to add the '.update()' part for the J=2-1.
-fixed frequency being used for J=2-1... another typo

Fix silly bug

---

pyspeckit/spectrum/models/lte_molecule.py

Fixes issue #353 as per problem noted by @yyamato-as.

Fix for lte_molecule optical depth in #353

---

docs/example_LTE_lineforest.py
docs/examples.rst
docs/lte_molecule_model.rst
pyspeckit/spectrum/models/lte_molecule.py
pyspeckit/spectrum/plotters.py

Comparing to XCLASS as a benchmark revealed some bad assumptions (optical depth adds, not intensity, for example).
This PR fixes those bad assumptions.
https://github.com/pyspeckit/pyspeckit-tests/pull/29

Radiative Transfer fixes for the LTE molecule

---

pyspeckit/spectrum/classes.py
pyspeckit/spectrum/units.py

Fix some syntax issues that raise warnings

---

docs/lte_molecule_model.rst
pyspeckit/spectrum/models/lte_molecule.py
pyspeckit/spectrum/models/model.py

minor docstrings updates as I'm reading through the Pyspeckit doc (trying to understand what's the best way to include Models for LTE rovibrational molecular spectra)

docstring update, fix latex in equations

---

CITATION.cff

here's what I could scavenge for #362, I don't think Jonny has ORCID, right @jdhenshaw?

add known orcid links

---

pyspeckit/cubes/SpectralCube.py

Pass kwargs onto file reading for cubes

---

pyspeckit/spectrum/units.py

See https://github.com/astropy/astropy/issues/14514

astropy now passes args to _new_view

---

pyspeckit/spectrum/models/lte_molecule.py

In a recent astroquery update (not yet merged), table column names will change for CDMS.

CDMS tables have names changed

---

pyspeckit/config.py

Refactor config.py for deprecation

---

pyspeckit/spectrum/models/lte_molecule.py

@abulatek this _should_ fix the HCO+ search issue in a few different ways.

make the molecule search function more robust & flexible
