pyspeckit/pyspeckit

pyspeckit/spectrum/models/tests/test_astropy_models.py
```
___________________________________________________________________________________ test_powerlaw ___________________________________________________________________________________
scale = 5.0, alpha = 2.0
def test_powerlaw(scale=5., alpha=2.):
x = np.linspace(10,100)
y = scale * (x)**(-alpha)
>      plm = astropy_models.PowerLawModel(1,1,1)
E      AttributeError: 'module' object has no attribute 'PowerLawModel'
```
=> AttributeError in test_astropy_models.py:12

pyspeckit/spectrum/fitters.py
bugfix: if vheight has previously been set, it needs to be re-set to False whenever multifitter is called
=> BUGFIX: vheight reset

docs/cubes.rst, pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/mapplot.py, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/units.py, pyspeckit/wrappers/fitnh3.py
The Cube component of pyspeckit was nearly undocumented.  This PR adds documentation.  In the process, I also refactored some of the unit/units stuff so that the singular is preferred (but the plural is still allowed, for now).
=> Add documentation to cubes

pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/fitters.py, pyspeckit/wrappers/fitnh3.py
And add a regression test for a newly discovered bug in which `_sort()` was happening after instead of before the instantiation of specfit.  `specfit.crop` was also not resetting the `spectofit`.
=> Fix the NH3 multifit test

examples/ammonia_fit_example.py, examples/ammonia_vtau_fit_example.py, examples/doublet_example.py, examples/hcn_cube_test.py, examples/voigt.py, pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/interactive.py, pyspeckit/spectrum/models/ammonia.py, pyspeckit/spectrum/models/inherited_voigtfitter.py, pyspeckit/spectrum/models/model.py, pyspeckit/wrappers/fitnh3.py
Since we have removed `peakbgfit` and `singlefit`, whose purpose was to automatically fit a single-peaked spectrum with an optional background, we still should have a way to input "reasonable" guesses automatically.  So the `specfit` call should accept `guesses='moment'` and should cal the appropriate moment tool to set up the guesses.  In order for this to work, a given model must have a `moments` method defined.
cc @dinossimpson - you have enough to deal with already, but this should be a relatively straightforward enhancement.
Affected tools from the removal of `peakbgfit` include at least:
* `wrappers/fitnh3.py`
* `tests/test_nh3_multi.py`
=> Add guesses='moments'

.travis.yml, REQUIREMENTS, pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/cubes.py, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/units.py, pyspeckit/wrappers/fitnh3.py
Cubes can have the spectra on axes other than the third (though why would you do that? it's insane?!!?!)
This is a quick workaround for such cubes, though the long-term better solution is to use `SpectralCube.read` as the only cube reader (just like we want to use specutils to read 1D spectra)
=> Cubes with different specaxes

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/plotters.py
```
Traceback (most recent call last):
File "<ipython-input-34-e23bed8a5063>", line 1, in <module>
spectrum.plotter()
File "/Users/adam/repos/pyspeckit/pyspeckit/spectrum/plotters.py", line 202, in __call__
self.plot(**kwargs)
File "/Users/adam/repos/pyspeckit/pyspeckit/spectrum/plotters.py", line 293, in plot
self.reset_limits(use_window_limits=use_window_limits, **reset_kwargs)
File "/Users/adam/repos/pyspeckit/pyspeckit/spectrum/plotters.py", line 370, in reset_limits
ymaxval = ((self.Spectrum.data[xpixmin:xpixmax]).max()-self.ymin.value)
AttributeError: 'float' object has no attribute 'value'
```
@dinossimpson this is related to your work
=> ymin.value is called on a non-quantity

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/models/ammonia.py, pyspeckit/spectrum/models/ammonia_hf.py, pyspeckit/spectrum/plotters.py
I think the chi-square calculation for fits on masked arrays (numpy.ndarray) is incorrect.  I can't replicate the chi-square value, and the degrees of freedom value isn't reduced by the length of the mask.
In the example below, wave, flux, and error are (unmasked) numpy.ndarray's.
spec = pyspeckit.spectrum.classes.Spectrum(xarr=wave,data=flux,error=error)
spec.data.mask = np.isnan(spec.data)
spec.data.mask[32:35] = True
spec.specfit(fittype='myfunc',guesses=[blah,blah2,blah3],quiet=False,multifit=False)
=> Specfit with masked arrays

pyspeckit/spectrum/units.py
This fixes a bug in the refX_unit initialization. If refX was passed as a Quantity refX_unit stayed None because of line 339.
=> fix in refX_unit initialization

examples/n2hp_cube_example.py, pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/units.py
This PR addresses https://github.com/pyspeckit/pyspeckit/issues/59#
When input_array is not a Quantity, numpy.ndarray or already a SpecAxis generate_xarr will raise a TypeError describing the error. I noticed that in the example mentioned in the issue, there is a call to load_fits from spectal-cube which produces the input_array.
Also, I added a commented out initialization for self._unit in Spectrum.`__init`__ in case unit=None which I think is the case that produces the error in https://github.com/pyspeckit/pyspeckit/issues/48.
=> Added error description in TypeError in units.py: generate_xarr 

pyspeckit/spectrum/units.py
refX_unit modified into a property and returns refX.unit (same for refX_units)
I added a log.warning when a user tries to set refX_unit directly but it spams alot!
=> refX_unit as a property

pyspeckit/cubes/SpectralCube.py
I'm running fiteach on a 16x14 pixel cube and I keep getting this error:
```python
IndexError: index 16 is out of bounds for axis 0 with size 16
```
Sometimes it's for index 14 and axis 1, depending on how many cores I'm running on.
This is the traceback if I'm running on 2 cores:
```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/Volumes/Storage/Observing/APO/Orion_cubes/fitscript_h2_orion.py in <module>()
44                 (True,True)], 
45                 parlimits=[(0.9,1.4), (0,16), (21210,21225), (0.5,5)],
---> 46                 signal_cut=2,start_from_point=(8,7))
47 
48 # plot the fits as images (you can click on these to see the spectra + fits) …
```
=> index out of bounds with fiteach

pyspeckit/cubes/SpectralCube.py
A Python user reported an issue where they pip installed pyspeckit then got an importerror for spectral-cube. Maybe spectral-cube should be listed as a dependency in install_requires?
=> Add spectral-cube to install_requires in setup.py

pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/fitters.py
See https://github.com/GBTAmmoniaSurvey/GAS/issues/45
It is not obvious how this happens, but it results from the fitter *returning* values 1 ULP out of range.
Workaround: extra validation.  Unfortunately, this adds some (hopefully tiny) overhead to each fit.
=> fiteach can result in parameters out of range by 1 ULP

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/interactive.py, pyspeckit/spectrum/plotters.py, pyspeckit/spectrum/tests/test_eqw.py
I am trying to measure equivalent widths for low-resolution optical spectra, but am encountering an error in the actual measurement. I'm getting an extremely small EW, an uncertainty on the order of 10e-11, and the Voigt profile fit does not appear on the final plot. It seems that the eq width procedure is trying to integrate to a point. 
Below is my code and the output plot. 
I ran this same code a few months ago and didn't have this issue (see below).
=> measuring EQWs for low-res optical spectra 

pyspeckit/spectrum/fitters.py
=> Fix loophole where 'parinfo' is checked but 'guesses' are not

pyspeckit/spectrum/plotters.py
line_id won't work with quantities right now due to matplotlib/numpy array creation issues.
=> Fix for line_id + quantities

pyspeckit/spectrum/plotters.py
Often, `T_{MB}` or other scales are intended when the units are Kelvin
=> Remove hard-coded K->T_A* label

pyspeckit/spectrum/classes.py
If you try to give a `Spectrum` a quantity for the data at the moment, it will die kind of like this:
```
NotImplementedError                       Traceback (most recent call last)
<ipython-input-24-7a72129aa2ad> in <module>()
----> 1 spec = ps.Spectrum(data=c[:,50,50], xarr=c.spectral_axis)
/Users/anon/anaconda/lib/python2.7/site-packages/pyspeckit/spectrum/classes.pyc in __init__(self, filename, filetype, xarr, data, error, header, doplot, maskdata, unit, plotkwargs, xarrkwargs, **kwargs)
178             else:
179                 self.data = np.ma.masked_where(np.isnan(self.data) + np.isinf(self.data), self.data)
--> 180                 self.error = np.ma.masked_where(np.isnan(self.data) + np.isinf(self.data), self.error)
181 
182         # it is very important that this be done BEFORE …
```
=> Allow `data` to be passed as a Quantity

pyspeckit/spectrum/tests/test_units.py, pyspeckit/spectrum/units.py
This affects only small corners of pyspeckit, but in particular the NH3 wrapper module
=> Bugfix: in_range needs to check units before comparing

pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/models/ammonia_constants.py
Important bug: @keflavich @low-sky @rfriesen
I compared the frequencies for the HFS components of NH3(1,1) from Lovas (http://pml.nist.gov/cgi-bin/micro/table5/search.pl) with those used in `pyspeckit`, and there is an offset due to the wrong rest rfequency used.
```
In [1]: import astropy.units as u
In [2]: freq=23692.9265*u.MHz
In [3]: rest11_pyspeckit=23.694506*u.GHz
In [4]: freq.to(u.km/u.s, equivalencies=u.doppler_radio(rest11_pyspeckit))
Out[4]: <Quantity 19.984471818482156 km / s>
In [5]: new_rest11=23.6944955*u.GHz
In [6]: freq.to(u.km/u.s, equivalencies=u.doppler_radio(new_rest11))
Out[6]: <Quantity 19.851630375538335 km / s>
```
while the offset for the first component in `pyspeckit` is `19.8513`
=> Offset between NH3(1,1) frequencies

docs/example_n2hp.rst, examples/n2hp_cube_example.py, examples/n2hp_example.py, pyspeckit/cubes/SpectralCube.py
This error raised when I try to fit N2H+ cube following
[this link](http://pyspeckit.bitbucket.org/html/sphinx/example_n2hp_cube.html)
Seems straightforward to fix (hopefully).
```python
45                 signal_cut=6, # minimize the # of pixels fit for the example
46                 start_from_point=(168,32), # start at a pixel with signal
---> 47                 errmap=errmap
48                 )
49     # There are a huge number of parameters for the fiteach procedure.  See:
/home/kwang/anaconda/lib/python2.7/site-packages/pyspeckit-0.1.18.dev1933-py2.7.egg/pyspeckit/cubes/SpectralCube.pyc in fiteach(self, errspec, errmap, guesses, verbose, verbose_level, quiet, signal_cut, usemomentcube, blank_value, integral, direct, absorption, use_nearest_as_guess, use_neighbor_as_guess, …
```
=> ValueError: Map is all NaNs or infs.  

examples/ammonia_fit_example.py, examples/ammonia_vtau_fit_example.py, pyspeckit/spectrum/models/ammonia.py
This also fixes some minor issues:
* When N_tot was specfied as a large number, the fits were never accurate.  I
now force Ntot to be specified logarithmically, which means the errors are
logarithmic errors, which should be more representative of how they come into
play in the radiative transfer equation.
* `thin` didn't do anything
* Errors were wrong in the examples because there was no spectral error included
* The examples were fitting T_kin with a single line, resulting in degenerate fits,
so now the degenerate parameters are kept fixed.
=> Fixes to ammonia examples, and add a legitimate ammonia-thin fitter

pyspeckit/cubes/SpectralCube.py
```
In [97]: blah = cube11.get_spectrum(512,512)
c
In [98]: cube11.un
cube11.unit   cube11.units  
In [98]: cube11.unit
Out[98]: 'K'
In [99]: blah.unit
Out[99]: 'JY/BEAM'
```
=> cube.get_spectrum(...) does not preserve cube unit

pyspeckit/spectrum/baseline.py, pyspeckit/spectrum/classes.py
Continuum fitting will fail pretty badly if the X-axis units are huge numbers,
e.g. Hz.  The default is therefore best set to 'pixels' for the fit unit...
=> Fix some issues with Baselines

pyspeckit/spectrum/readers/fits_reader.py
I have been experiencing an issue with pyspeckit v0.1.14, in which loading a 1D FITS spectrum results in a xarr which is offset from the expected xarr by a factor of the xarr.refX and the associated data values are flipped L-R. 
E.g., the corect spectrum should appear as: in this image 
But after issuing the the following pyspeckit commands,
```
sp = pyspeckit.Spectrum('demo.fits')
sp.plotter()
```
Appears as so: 
The FITS file I used to demonstrate this behavior: http://privon.com/upload/demo.fits
The FITS fine in question was written out using pyfits (using sp.write() ), after calibration and processing. I assume something could be wrong with the FITS headers that would lead to this behavior, but if that's the case it might also suggest an issue with the way pyspeckit …
=> xarr offset and flip when loading/plotting 1D spectra

.travis.yml, pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/models/model.py
I'm trying to use `measure_approximate_fwhm()` to measure FWHM for a set of absorption lines. The following code runs, but yields an extremely small measurement (`fwhm = 0.00899764977619`). 
sp = pyspeckit.Spectrum(filename)
sp.xarr.units = 'micron'
sp.xarr.xtype = 'wavelength'
sp.plotter(xmin=1.250, xmax=1.255, ymin=0, errstyle = 'fill', color='black')      
sp.specfit(plot=True, fittype='voigt', color='blue')
fwhm = sp.specfit.measure_approximate_fwhm(threshold='error', emission=True, interpolate_factor=1024, plot=True, grow_threshold=1)
sp.plotter.refresh()
print fwhm
xarr_fit_units = 'microns'
plt.ylabel('Normalized Flux')
plt.xlabel('Wavelength ($\mu m$)')
It seems like the code is incorrectly calculating the FWHM, since the line that should be drawn at the FWHM is well below the …
=> specfit.measure_approximate_fwhm() emission=False fails

pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/models/hyperfine.py, pyspeckit/spectrum/models/n2dp.py, pyspeckit/spectrum/plotters.py, pyspeckit/wrappers/fitnh3.py
@keflavich  @Punanova  This is a continuation to issue #117 , because it is using the same data, but we have a different issue.
We run the following script and the fit is performed, but it can not be loaded. The problem is important because we want to load the fit results afterwards, and the system breaks, but the results from the fit are OK when inspected before calling  `write_fit()`
```
import matplotlib.pyplot as plt
plt.ion()
file_in='Core2_N2Dp_21_fine5.fits'
file_gauss= 'Gaussian_fitted_parameters3.fits'
cube = pyspeckit.Cube(file_in)
F=False
T=True
cube.fiteach(fittype='gaussian',  guesses=[1.3, 6.7e3, 0.3e3], 
verbose_level=1, signal_cut=5, limitedmax=[F,T,F], maxpars=[0,8.0e3,1.0e3],
limitedmin=[T,T,F], minpars=[0,5.0e3,0.05e3], use_neighbor_as_guess=True, …
```
=> problem loading fit from file

pyspeckit/spectrum/models/hyperfine.py, pyspeckit/spectrum/models/n2dp.py, pyspeckit/spectrum/plotters.py, pyspeckit/wrappers/fitnh3.py
@jpinedaf 
Trying to show the result of N2D+ hyperfine structure fit I've got an error with loading the spectral cube. The data origin is GILDAS software, the fits header is shown below. Here is the sample:
```
cube = pyspeckit.Cube(file_in)
import matplotlib.pyplot as plt
cube.plot_spectrum(10,10)
```
until here the code works
```
from pyspeckit.spectrum.models import n2dp
cube.Registry.add_fitter('n2dp_vtau', pyspeckit.models.n2dp.n2dp_vtau_fitter, 4)
cube.plot_spectrum(10,10)
```
The error message:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-16-63e866b5228d> in <module>()
----> 1 cube.plot_spectrum(xmax,ymax) …
```
=> Problem displaying the fits

pyspeckit/cubes/cubes.py, pyspeckit/cubes/tests/test_cubetools.py
It seems that subimage_integ doesn't update the header properly when cropping the sky coordinates. This code should reproduce the issue:
```python
import matplotlib.pyplot as plt
import aplpy
from astropy.io import fits
import os
if not os.path.exists('foo.fits'):
from astropy.utils.data import download_file
tmp_path = download_file('https://db.tt/oleS9xD6')
try:
os.rename(tmp_path, 'foo.fits')
except OSError:
import shutil
shutil.move(tmp_path, 'foo.fits')
spc = pyspeckit.Cube('foo.fits')
xcen, ycen = 4.5, 4.5
xwidth, ywidth = 2.5, 2.5
cutData, cutHead = pyspeckit.cubes.subimage_integ(spc.cube, xcen, xwidth, 
ycen, ywidth, vrange=(0,9), zunits='pixels', 
units='pixels', header=spc.header)
fits.writeto('cut.fits', cutData, cutHead, clobber=True)
xlo = …
```
=> Opposite CRPIX adjustment in subimage_integ?

pyspeckit/spectrum/classes.py, pyspeckit/spectrum/models/hyperfine.py
We have developed a test that compares the HFS fit from `pyspeckit` and `GILDAS/CLASS`. The FITS and CLASS files and the python and CLASS scripts to perform the fits are also available here: 
https://github.com/Punanova/fit_N2Hp
For the same spectrum we get a similar fit, but a much larger uncertainty. These are the best fit spectrum using both methods
The centroid velocities are similar (after taking into account the 7km/s offset due to some annoying non-standard FITS keyword).
```
parameter | CLASS | pyspeckit
---------- | --------------------------- | --------------------
Vlsr | 7.003 $+-$ 0.001   | 7.003 $+-$ 0.022
FWHM |   0.240 $+-$ 0.001  | 0.240 $+-$ 0.056  (FWHM=2.3548*sigma)
tau      |   7.169 $+-$ 0.077    | 7.2 $+-$ 9
```
@keflavich any ideas of why is `pyspeckit` getting such …
=> errors in N2H+ line are *much* larger than CLASS

pyspeckit/spectrum/interactive.py, pyspeckit/spectrum/plotters.py
This is a weird bug that probably only affects python3 and had something to do with ordering of dictionary keys.  I've fixed it by using the appropriate components of the mpl API, I hope
=> UI bugfix: re-trying to fit interactively in an over-plotted window fails sometimes

pyspeckit/spectrum/models/lte_molecule.py
This adds a simple model for LTE molecular lines.  It is not tested or used in
practice yet, but it is used in, e.g.,
https://github.com/keflavich/h2co_modeling/blob/master/h2co_modeling/lte_model.py
=> Add a new model: LTE lines

CHANGES.rst, pyspeckit/spectrum/models/hyperfine.py, pyspeckit/spectrum/models/tests/test_astropy_models.py, pyspeckit/spectrum/models/tests/test_hyperfine.py
Optically thin fit does not reproduce N2H+(1-0) hyperfine structure and returns too high T_ex (e+11) and sigma, two times bigger than a real value (calculated with CLASS or optically thick approach).  
The criterion we use to decide which fit results to use, optically thin or thick, is tau/delta_tau>=3. Most of N2H+(1-0) spectra will pass this criterion, however there are points on the edges of the cores where N2H+ line is not strong enough so we need optically thin approach. 
I've checked some of such points and optically thin fit does not give good result, please see the thin and thick fits of the same spectrum in the attached figures. The spectrum used to produce the figures is here https://github.com/Punanova/thick_vs_thin/blob/master/73-core2_N2Hp.fits
.
=> Poor optically thin N2H+(1-0) fit

pyspeckit/cubes/SpectralCube.py
related to https://github.com/GBTAmmoniaSurvey/GAS/issues/68
=> Bugfix: Cube.get_spectrum can provide invalid parameters

pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/models/model.py, pyspeckit/spectrum/models/tests/test_hill5.py
It looks like the Hill5 model is broken, because it might be missing some parameters: `npeaks` 
I'm using `pyspeckit` version `0.1.19.dev2152`
```python
import numpy as np
import astropy.units as u
from pyspeckit.spectrum.models import hill5infall
snr_min = 5
cube = pyspeckit.Cube(file_in)
cube.xarr.refX = freq_line
cube.xarr.velocity_convention = 'radio'
cube.xarr.convert_to_unit('km/s')
rms_map = cube.slice(6.0, 6.6, unit='km/s').cube.std(axis=0)
peaksnr =  cube.slice(vmin, vmax, unit='km/s').cube.max(axis=0)/rms_map
cube.Registry.add_fitter('hill5_model', pyspeckit.models.hill5infall.hill5_model, 5)
sz=np.shape(Vlsr)
my_guess=np.empty( (5,sz[1],sz[0]) )
my_guess[0,:,:]=1.0
my_guess[1,:,:]=7.0
my_guess[2,:,:]=0.1
my_guess[3,:,:]=0.2
my_guess[4,:,:]=1.0
print('start …
```
=> Hill5 model is broken

pyspeckit/cubes/SpectralCube.py
Cube indices and fit number are missing in the string formatting for "no specific error" failure in fiteach function.
=> Missing formatting for a fiteach error

pyspeckit/cubes/SpectralCube.py
Currently, get_modelcube() throws an error if there was never a call to mapplot()
=> Calculating a model cube with no prior calls to mapplot()

pyspeckit/cubes/SpectralCube.py
CubeStack class doesn't have CubeStack._modelcube attribute defined, but it does have get_modelcube() method. This causes CubeStack.get_modelcube() to crash. Initializing _modelcube as None in CubeStack solves the problem.
=> get_modelcube fix for CubeStack class

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/models/model.py, pyspeckit/spectrum/units.py
`sp.xarr.min()`, for example, would previously result in another
`SpectroscopicAxis` instance, which did not evaluate usefully in boolean
comparisons (e.g., `bool(SpectroscopicAxis([False]))` might have evaluated to
`True`).  This fixes the issue by overriding `_new_array` (or something...) in
the same way as `astropy.units.Quantity`
=> Fix dimensional reduction issue in SpectroscopicAxis

pyspeckit/cubes/tests/test_cubetools.py
1. Added a function for generating test cubes. The cubes generated are basically Gaussian ellipsoids in ppv-space with some noise on top.
2. Added two preliminary tests, one that fits a gaussian to a cube and compares its parcube to original line widths; and another that makes sure that there isn't anything wrong with get_modelcube function (c.f. https://github.com/pyspeckit/pyspeckit/pull/131). Both still need some improvements in terms of passing criteria.
=> Framework for cube tests

pyspeckit/cubes/SpectralCube.py
Local variable `smooth` passed to the [smooth method](https://github.com/pyspeckit/pyspeckit/blob/master/pyspeckit/cubes/SpectralCube.py#L1162-L1185) clashes with the following import:
```python
from ..spectrum import smooth
```
resulting in an error [here](https://github.com/pyspeckit/pyspeckit/blob/master/pyspeckit/cubes/SpectralCube.py#L1175). This PR renames the local float value `smooth` into `factor` to avoid variable clashes.
=> Fix for cube smoothing

pyspeckit/cubes/SpectralCube.py
The title is self-explanatory: setting `use_nearest_as_guess=True` causes a `NameError` when making a call to `fiteach()`. From looking at the source file this looks like a bug - the `distance` variable - on which `use_nearest_as_guess` depends - isn't defined anywhere since de9c0c1b6252e3c2571b45b9b7a22013b2a50baf was pushed. Not sure what should be done with it, so raising it as an issue.
=> use_nearest_as_guess breaks fiteach()

pyspeckit/spectrum/tests/test_units.py, pyspeckit/spectrum/units.py
Is there a way, given a quantity valid as a `SpectroscopicAxis` coordinate, to convert it into a nearest pixel value? Can't seem to find a way to do this without converting the whole axis to that unit.
So, given this example set-up,
```python
import astropy.units as u
from pyspeckit.cubes.tests import test_cubetools
test_cubetools.make_test_cube()
spc = pyspeckit.Cube('test.fits')
spc.xarr.velocity_convention = 'radio'
spc.xarr.refX = 100 * u.GHz
```
what I'm looking for is this:
```python
spc.xarr.x_to_pix(2) # for 2 km/s
```
but for units other than `spc.xarr.unit`
Currently this works:
```python
spc.xarr.convert_to_unit('GHz')
spc.xarr.x_to_pix(99.9986)
```
but I feel that it's an overkill.
=> SpectroscopicAxis: best way for unit to pixel mapping?

.travis.yml, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/readers/tests/test_specutils_reading.py, pyspeckit/spectrum/tests/test_units.py, pyspeckit/spectrum/units.py
This was always the intended behavior, but it broke during the transition to using astropy quantities in general.
TODO:
=> Allow quantities when .slice'ing

scripts/README.rst, scripts/pyspeckit.py, scripts/pyspeckit_script.py
Unfortunately, the *name* of the script still isn't fixed.  It is now
`pyspeckit_script.py` instead of just `pyspeckit`, which is what I wanted.
=> Fix some issues with the pyspeckit script

pyspeckit/cubes/SpectralCube.py
For review: a few changes that make it much cleaner to use moments as guesses for cubes:
* 24553aa allows `momenteach()` to pass `vheight=False` as default. If set to true, calling `fiteach(usemomentcube=True)` will grab a guess from the `momentcube` that is one element longer than needed. This change is consistent with the [1d fitter](https://github.com/pyspeckit/pyspeckit/blob/master/pyspeckit/spectrum/fitters.py#L602) case, which also passes `vheight=False` to `moments`.
* currently, the `TEST BLOCK` in `fiteach` doesn't actually give a chance for `usemomentcube=True` to set the guesses from the momentcube if the guesses aren't set or are of the wrong length. This diminishes the need for the keyword in the first place, as one could just pass `guesses=spc.momentcube` instead. I added a …
=> better fiteach + moments functionality

pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_cubetools.py
Fix the issue noted by @jpinedaf here: https://github.com/GBTAmmoniaSurvey/GAS/pull/119/files/00412053986274dc07ddd8ad17ed19e3ec78721e#r61290961
The fix isn't 100% guaranteed to work; it doesn't check the validity of the
parameters for each pixel.  However, if the parameters were written by a valid
fit from `fiteach`, then they all should be in bounds and should therefore be
valid.  The only check performed here is that *at least one* of the parameters
is nonzero for each pixel.
Also added a progressbar.
=> Fix parameter cube loading issues

pyspeckit/cubes/SpectralCube.py
A follow-up on #163 - didn't think about it before. If get_modelcube() gets an ammonia parcube to crunch, it will break a tooth on any `NaN` values passed along with it, so it should probably just ignore those pixels.
```python
In [7]: sp.specfit.get_full_model(pars=[np.nan]*12)
ValueError: ntot, the logarithmic total column density, must be in the range 5 - 25
```
Also, is there any particular reason to fill the model cube with zeros instead of `NaN` values? Just curious.
=> Should get_modelcube() filter out NaN values?

pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_cubetools.py, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/tests/test_fitter.py
When getting a spectrum from `Cube.get_spectrum` method, the models added to the spectrum seem to get lost when specfit is called. Having a hard time understanding why this happens. Doesn't a `Spectrum` object just pass own its own Registry to `Specfit` one?
Adding a fitter directly to the parent `Cube` object before calling `get_spectrum` - a commented line in a script below - is a workaround for the issue.
```python
from pyspeckit.spectrum.models import n2hp
spc = pyspeckit.Cube(filename)
spc = spc.slice(*spc_cut, unit='km/s')
spc.xarr.velocity_convention = 'radio'
sp=spc.get_spectrum(*start_yx[::-1])
sp.Registry.add_fitter('n2hp_vtau', n2hp.n2hp_vtau_fitter, 4)
assert 'n2hp_vtau' in sp.Registry.multifitters
assert 'n2hp_vtau' in sp.Registry.npars …
```
=> specfit does not always inherit its own Registry

pyspeckit/cubes/SpectralCube.py
Hello! I've recently started working with pyspeckit with @jpinedaf, but I'm still quite a beginner.  I want to fit an ammonia spectrum (1-1) but for some reason the `use_nearest_as_guess = True` parameter in the `.fiteach()` function gives me the following error message:
> Traceback (most recent call last):
>   File "test_linefitting.py", line 70, in <module>
>     errmap=errmap, position_order = 1/peaksnr, maskmap=planemask, multicore=2)
>   File "/home/USER/miniconda3/envs/python2/lib/python2.7/site-packages/pyspeckit-0.1.19.dev2315-py2.7.egg/pyspeckit/cubes/SpectralCube.py", line 940, in fiteach
>     result = parallel_map(fit_a_pixel, sequence, numcores=multicore)
>   File "/home/USER/miniconda3/envs/python2/lib/python2.7/site-packages/pyspeckit-0.1.19.dev2315-py2.7.egg/pyspeckit/paral …
=> use_nearest_as_guess=True gives error message

docs/examples.rst
They reference papers and link to the github source.
So far, all of the examples are for cubes because I was specifically searching
for cubey examples.
@punanova, @vlas-sokolov: you both have some code on github that uses
pyspeckit.  Are you interested in having that linked?  Please submit a PR or
post a link if you'd like to be referenced from this page.
=> Create some new "real world" examples on the example page

pyspeckit/spectrum/readers/hdf5_reader.py
I recently got the following error message when importing pyspeckit in ipython (3.2.0, python v. 2.7):
```
In [6]: import pyspeckit
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting …
```
=> pyspeckit broke!

pyspeckit/spectrum/toolbar.py, pyspeckit/spectrum/velocity_frames.py
In trying to build pyspeckit locally I found a couple places where print statements are still used.
=> Change print statement to print function

pyspeckit/spectrum/models/formaldehyde_mm.py
@keflavich -- I think there was a change to units that wasn't passed down to the mmh2co fitter.  Comparing values seems to work.  Probably some PEP8 stuff is wrong that python can't handle.
=> MM H2CO fix

pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/classes.py, pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/interactive.py, pyspeckit/spectrum/tests/test_units.py, pyspeckit/spectrum/units.py
If you cropped a spectrum or sliced an `xarr`, the resulting `dxarr` (and therefore `cdelt`) would be incorrect.
=> Correct dxarr creation on cropping

pyspeckit/spectrum/fitters.py
Got this error this morning, thought I was still asleep: 
`Fit number 0 at 25,51 failed on error 45.0 is greater than the upper limit 40.0`
=> Typo in upper limits error message

examples/n2hp_cube_example.py, pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_cubetools.py, pyspeckit/spectrum/classes.py
I'm getting an unexpected behavior when running `fiteach` on a dummy gaussian cube. A fit with a good initial guess doesn't converge for a significant fraction of the pixels, despite good signal-to-noise ratios in them.
It doesn't seem to be an issue of the underlying non-linear least squares code too - if I just do a for-loop over all (x,y) positions and fit every spectrum using `specfit` with the same initial guesses, the issue disappears:
```python
import numpy as np
import matplotlib.pylab as plt
from pyspeckit.cubes.tests.test_cubetools import make_test_cube
make_test_cube((100,10,10), outfile='test.fits', sigma=(10,5))
spc = pyspeckit.Cube('test.fits')
spc.fiteach(fittype = 'gaussian',
guesses=[0.7,0.5,0.8])
sigma_fiteach = spc.parcube[2].copy()
for y,x in …
```
=> fiteach doesn't fit certain pixels, specfit does

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/models/lte_molecule.py
As reported by E. Mills: if you load data with dtype=float32, it will fail to
fit (with either mpfit or lmfit) because the step size is equivalent to zero
when expressed as a 32-bit float.  This PR fixes the issue.
=> Fitting float32 spectra will result in gnorm=0 errors

pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/fitters.py
It was producing too many warnings in tests and isn't often used, it just makes
computations more expensive.
@vlas-sokolov, you're one of the main users of this feature at present: any
opposition to this change?
=> Change the default integral=True to False in fiteach

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/plotters.py
(I apologize for the long post in advance...)
I have a module which measures absorption lines in optical spectra using pyspeckit, and I'm seeing a pretty substantial memory leak. I think it's not in my code, but I was hoping that the "hive mind" could help...
Here's the (pseudo-) code I use. The example spectra was a 1.5MB .fits file:
```python
#Loading the spectrum:
if (certain instruments):
apertureList = [pyspeckit.Spectrum(spectrumFilename)]
else: # (other instruments)
apertureList = pyspeckit.wrappers.load_IRAF_multispec(spectraFilename)
for roughSpec in specList:
roughSpec.smooth(smooth=2,downsample=False)
pylab.ion()    # Put matplotlib into interactive mode
plotFigure = pyplot.figure(num='Line Analysis')
for (line info) in (long (~1300) list of atomic lines):
smoothSpec = …
```
=> Memory leak in specfit?

pyspeckit/spectrum/plotters.py
This often resulted in annoying error messages of the form:
```
File "/Users/adam/repos/pyspeckit/pyspeckit/spectrum/plotters.py", line 642, in line_ids
equivalency = doppler(self.Spectrum.xarr.refX)
File "/Users/adam/repos/astropy/astropy/units/equivalencies.py", line 248, in doppler_radio
assert_is_spectral_unit(rest)
File "/Users/adam/repos/astropy/astropy/units/equivalencies.py", line 532, in assert_is_spectral_unit
raise UnitsError("The 'rest' value must be a spectral equivalent "
UnitsError: The 'rest' value must be a spectral equivalent (frequency, wavelength, or energy).
```
=> Don't require refX for line_id plotting

pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_cubetools.py
Cube headers and cube wcs's were untouched by the likes of `spc.slice()`. This PR brings header modification into the fold. If we're good to go I'll write up the update for a new wcs instance as well. Is slice() the only place the spectral axis needs to be modified?
Most importantly, this time it comes with a test!
=> cube slice now updates header!

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/units.py
This can come up with all-zero spectra, which are basically invalid anyway, or those corner cases where the median is actually zero
=> Prevent divide-by-zero renormalization

pyspeckit/spectrum/readers/read_class.py
This change allows to pass strings to the `read_class` function rather than bytes. A new option is added to select spectra by the line name in the CLASS headers.
=> Use Unicode strings in CLASS indices

pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_cubetools.py
Squashing two spectral cubes via `CubeStack` class can sometimes break in Python 3. If in the following example the header of `nh311.fits` contains either `HISTORY` or `COMMENT` keywords, calling `CubeStack` results in an infinite loop:
```python
from pyspeckit import Cube, CubeStack
nh311, nh322 = Cube('nh311.fits'), Cube('nh322.fits')
cubes = CubeStack([nh311, nh322])
```
The new header is a shallow copy of the original one in the init method. Essentially, this is what happens when `CubeStack()` is called:
```python
from astropy.io import fits
head = fits.Header()
head['foo'] = "just a regular keyword", "nothing to worry about"
head['HISTORY'] = "you can't contain me!"
head_new = head
for key, val in head.items():
head_new[key] = val
```
Now for Python 2 this simply results in a …
=> CubeStack.__init__ can get trapped in an infinite loop

pyspeckit/cubes/tests/test_cubetools.py
The noise for the test cube was uniformly - not normally - distributed. I edited the `make_test_cube` function to sample noise from Gaussian distribution and updated the tests to reflect the change. For instance, `test_get_modelcube` check now makes much more sense - after the fit, the cube residuals are broadly consistent with 1σ noise level.
Apart from that, I moved some import statements around, made minor edits, and added a docstring for `make_test_cube` function.
=> Changes in Cube tests

pyspeckit/spectrum/readers/read_class.py
This gives the MJD day of observations so the mid-exposure time can be obtained from
```
index['MJD'] + index['UT']/2./pi
```
It looks like this is correct from the documentation and it gives slightly different results than using the year number in DOBS but I may have done something wrong with that.
EDIT: CLASS developers have confirmed that 
```
index['DOBS'] + 60549  + index['UT']/2./pi
```
is the right formula for the mid-exposure time in MJD
=> Added MJD field to index

pyspeckit/spectrum/models/extinction.py, pyspeckit/spectrum/models/hydrogen.py, pyspeckit/spectrum/readers/read_class.py
trying to use:
pyspeckit.spectrum.models.hydrogen.find_lines(sp.xarr)
returned an error (traceback below) which has nothing to do with my input spectrum. It stems from hydrogen.py changing the xarr to 'microns', while astropy is looking for 'micron' (no s).
changing 'microns' -> 'micron' on line 214 of hydrogen.py (and re-compiling) fixed the problem in my installation (pyspeckit-c8c7ab014df0, downloaded from bitbucket 21-dec-2016, astropy version 1.2.1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-ea0c808fc7c8> in <module>()
----> 1 execfile('quantify_h30a.py')
/RESEARCH/BitBucket/msf_disks/quantify_h30a.py in <module>()
86 
87 …
=> hydrogen.find_lines has an incompatibility with astropy

pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_spectralcube.py
Latest numpy versions don't allow indexing with floats.
This demonstrates that there is a lot of untested stuff in pyspeckit's cubes...
=> Replace cube indexing with int-based indices

.travis.yml, pyspeckit/cubes/tests/test_cubetools.py, pyspeckit/mpfit/mpfit.py, pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/models/model.py, pyspeckit/spectrum/tests/test_fitter.py
For optical spectra that have units <10^-9, e.g., ~10^-16 erg/s/cm^2/AA, the data are rescaled prior to fitting in order to minimize numerical issues when fitting (though I admit I don't know if that's still a reasonable concern any more).  There is a bug in the existing code in which, when performing a multi-peak fit, only the *first* peak will be scaled.  If you repeat the fit, in all subsequent fits, all of the peaks will be appropriately scaled.  This is because the scaling was determined based on a parameter that was not set properly.
Thanks @granttremblay for pointing this out.
=> Bug: When rescaling, the first iteration will scale many parameters incorrectly

CHANGES.rst, pyspeckit/spectrum/fitters.py
Just as it says, register the ammonia model.
This would normally have been attached to issue #210 but there seems to be a
bug in my `hub`.
=> Partial fix for Issue 210: register cold_ammonia_model

pyspeckit/spectrum/smooth.py
Fixes #213 
I moved the int() typecasting to surround `round`. I tested this change with a quick reduction and boxcar smoothing worked with the numpy 1.12.0 indexing.
=> force roundsmooth to int for numpy deprecation of non-int indices.

pyspeckit/spectrum/models/ammonia.py, pyspeckit/spectrum/models/tests/test_ammonia.py
Looks like python2-style division caused `n_ammonia` method of `ammonia_model` to break when ran in Python 3. Here's a snippet (added to tests) that reproduces the issue:
```python
from pyspeckit.spectrum.models.tests.test_ammonia import make_synthspec
from pyspeckit.spectrum.models import ammonia
import numpy as np
kwargs = dict(lte=False, tkin=None, lines=('oneone', 'twotwo'))
redhot = dict(trot=25, tex=10, column=13, width=1, vcen=1)
bluecold = dict(trot=12, tex=7, column=13, width=.2, vcen=-1)
redhot.update(kwargs)
bluecold.update(kwargs)
sp_redhot = make_synthspec(**redhot)
sp_bluecold = make_synthspec(**bluecold)
sp = sp_redhot.copy()
sp.Registry.add_fitter('ammonia', ammonia.ammonia_model(), 6)
sp.specfit.fitter = sp.specfit.Registry.multifitters['ammonia']
sp.specfit.fitter.npeaks …
```
=> Ammonia model in Python 3 with npeaks>1

pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_cubetools.py
Pooling functionality already exists for several methods of `SpectralCube` class, and can be fairly easily ported to the `get_modelcube` method - which is what's being done in this PR.
All in all, this can achieve significant speed-ups for fairly large cubes and/or high values of `npeaks`:
```python
In [67]: %timeit spc._modelcube=None;spc.get_modelcube(multicore=8)
1 loop, best of 3: 1.47 s per loop
In [68]: %timeit spc._modelcube=None;spc.get_modelcube(multicore=1)
|===================================================================| 9.7k/9.7k (100.00%)         5s
|===================================================================| 9.7k/9.7k (100.00%)         5s
|===================================================================| 9.7k/9.7k (100.00%)         5s …
```
=> parallelize get_modelcube

pyspeckit/cubes/SpectralCube.py, pyspeckit/cubes/tests/test_cubetools.py
Okay, so this should fix #224. We now allow `Cube.fiteach` to take error cubes as input, via two ways:
1. The `errmap=` argument can take both 2D- and 3D-arrays now.
2. I also wrote in a check for the `errorcube` attribute for the `errmap is None` case, which is probably a more preferable way to specify errors anyway, because in that way the errors don't get lost during things like cube stacking, smoothing, and extracting spectra.
The regression test is inspired by #220, and checks if the errors from the non-uniform weighting case are reasonable for an ammonia fit with a very noisy (2,2) line.
=> Non-uniform channel weights for fiteach

pyspeckit/mpfit/mpfit.py, pyspeckit/spectrum/models/ammonia.py
So I've been profiling the ammonia model performance in `pyspeckit`, and, long story short, found out that both models and spectral fits can be improved to yield a large speed boost.
Here are the two areas I've addressed so far:
First of all, whenever `ammonia` function gets called, it tries to convert `xarr` into `GHz`. Somehow, this isn't optimized for speed in `astropy`, so in the end it ends up eating up a significant chunck of CPU power. This is fixed in 01142ec, and the `%timeit` results are given below in rows 2 and 3.
Now on to the largest performance boost. There's a `line_names` argument that gets passed to `ammonia` function, that, in turn, gets inherited by `_ammonia_spectrum`, specifying the inversion levels to calculate over. There are a few issues with this:
- [feature, not …
=> Ammonia models are now faster!

pyspeckit/spectrum/models/ammonia.py, pyspeckit/spectrum/models/tests/test_ammonia.py
@vlas-sokolov: the npeaks bit was something of a red herring.  There was a real
bug and I think it came from me trying to shortcut things in a weird way.  The
`npars` parameter was being incorrectly determined in `n_ammonia`.  Could you
confirm that this fixes #179?
[closes 179]
=> Add a regression test for issue 179 and fix it.

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/interactive.py
If an interactive `guesspeakwidth` session is started, includemask is reset to
be all False by default.  If no clicks are made to select regions, we should
assume *all* data are included.
=> Fix issue 247 - Initialize includemask

pyspeckit/spectrum/classes.py
This is an automated update of the astropy-helpers submodule to v2.0.2. This includes both the update of the astropy-helpers sub-module, and the ``ah_bootstrap.py`` file, if needed.
*This is intended to be helpful, but if you would prefer to manage these updates yourself, or if you notice any issues with this automated update, please let @bsipocz or @astrofrog know!*
=> Update astropy-helpers to v2.0.2

docs/example_pymc.rst, docs/example_pymc_ammonia.rst, docs/examples.rst, docs/fitting.rst, docs/install.rst, examples/example_pymc.py, examples/example_pymc_ammonia.py, examples/synthetic_LTE_ammonia_spectrum_example_witherrorestimates.py, examples/synthetic_nLTE_ammonia_spectrum_example_witherrorestimates.py, examples/synthetic_spectrum_example.py, pyspeckit/spectrum/models/ammonia.py, pyspeckit/spectrum/models/model.py
The new ammonia model is a more reasonable fitter to use in the LTE case
(T_rot=T_ex), since T_ex > T_rot is unphysical.
This comes with some examples that effectively test that case, but I'm not
running them as tests.  Instead, they're good for looking at how parameter
errors are affected.
=> New ammonia model with fitted T_r - T_ex, and examples

pyspeckit/spectrum/models/lte_molecule.py
It depends on vamdclib for the partition function, which is a bit annoying, but it works!
An example that is not very cheap to run:
```
fmin, fmax = (90,100)*u.GHz
freqs, aij, deg, EU, partfunc = get_molecular_parameters('CH3OH', fmin=fmin, fmax=fmax)
def modfunc(xarr, vcen, width, tex, column):
return generate_model(xarr, vcen, width, tex, column, freqs=freqs, aij=aij,
deg=deg, EU=EU, partfunc=partfunc)
fitter = generate_fitter(modfunc, name="CH3OH")
xarr = np.linspace(fmin, fmax, 1e6)
yarr = modfunc(xarr, 0, 5, 500, 1e15)
pl.plot(xarr, yarr)
```
=> Make the WIP LTE molecule a fully-functional tool

pyspeckit/spectrum/models/ammonia.py, pyspeckit/spectrum/models/tests/test_ammonia.py
Default to Tex > 2.73 to avoid <2.73-> crash errors.
=> Better defaults for Ammonia interactive guesser

pyspeckit/spectrum/baseline.py, pyspeckit/spectrum/interactive.py, pyspeckit/spectrum/models/ammonia.py, pyspeckit/spectrum/models/tests/test_ammonia.py, pyspeckit/spectrum/plotters.py, pyspeckit/spectrum/units.py
Just a whole bunch of corner cases I discovered.  One obvious one is that if
you start a new plotter in a window with an active pyspeckit session,
everything will go bad.  I need to implement some kind of garbage collection to
disconnect the callbacks when an axis is cleared.
I don't know how to do that yet.
=> Several fixes to interactivity

pyspeckit/spectrum/fitters.py
some users have tried accessing the `fitter` attribute of sp.specfit when it doesn't yet exist
=> add a warning to inform users if they're trying to use something undefined

pyspeckit/spectrum/classes.py
The idea is to allow straightforward initialization from a SpectralCube OneDSpectrum object.  However, I don't know if it works or if this is a good idea at all.
=> Allow Spectrum(xx) initialization if xx has hdu

pyspeckit/spectrum/fitters.py
`shift` variable was defined as a `list`, which breaks line 490:
```
midpt_index = np.argmin(np.abs(shifts-midval))
```
Simple solution implemented here is to change it to a `numpy.ndarray` .
=> fixed TypeError

pyspeckit/spectrum/models/model.py
If annotation is requested but the value is None, print value=None instead of crashing
cc @jdhenshaw
=> Improve the fail state for annotations if a value/error is None

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/models/model.py, pyspeckit/spectrum/parinfo.py
This will prevent erroneous reporting of "zero" error when really it is "None".  At the moment, though, it will also result in somehwat useless annotations in plots...
=> If errors can't be computed, set them to None

.travis.yml, docs/ammonia_model.rst, examples/fit_nh3_cube.py, examples/hcn_cube_test.py, pyspeckit/cubes/SpectralCube.py, pyspeckit/spectrum/models/ammonia.py, pyspeckit/wrappers/fitnh3.py
There are some persistent issues using fiteach w/ammonia, e.g. #307 and some others.
This PR enables a `skip_failed_fits` keyword in `fiteach` that will just.... hopefully...
skip over the failed fits.  It's a BAD idea to enable this in general, but I can't think of
what else to do right now.
=> Increase fiteach verbosity and work on ammonia fixes

docs/conf.py
This fixes the sphinx warning when building the docs:
```
WARNING: Support for evaluating Python 2 syntax is deprecated
and will be removed in Sphinx 4.0. Convert conf.py to Python 3
syntax
```
=> Migrate conf.py to python 3 syntax

pyspeckit/spectrum/fitters.py
legend.Legend.draggable was deprecated and it has been removed in recent
matplotlib relases:
https://matplotlib.org/3.1.1/api/api_changes.html#removals
https://github.com/matplotlib/matplotlib/pull/10050
=> Replace Legend.draggable with Legend.set_draggable

pyspeckit/spectrum/models/ammonia_constants.py
This is a fix for #351.  It may also (help) solve issue #330.  
There is an accounting error in the Ortho transitions of NH3; the J-values were indexed from 0,0, but were being treated as if they started at 3,3
=> Fix for issue 351

docs/install_via_GitHub.rst
In order to correctly install `pyspeckit` via GitHub, `pip install -e .` should be used instead of `python setup.py develop`.
=> Changed install command in docs for installing via GitHub

pyspeckit/mpfit/mpfit.py, pyspeckit/spectrum/baseline.py, pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/tests/test_units.py, pyspeckit/spectrum/units.py
This is to solve an error where sometimes, rather inexplicably (I tracked this down super far), `lmfit` turns perfectly valid values into NaNs if the errors are huge.
example:
```python
> self.errspec
masked_array(data=[10000000000.0, 0.7184141874313354,  ....  0.7184141874313354, 10000000000.0] ...)
```
causes
```
ipdb> _minpack._lmdif(func, x0, args, full_output, ftol, xtol, gtol, maxfev, epsfcn, factor, [1,1,1,1,1,0.1,])
DEBUG: Pars, kwarg keys: Parameters([('AMPLITUDE0', <Parameter 'AMPLITUDE0', value=5.538497979872734, bounds=[-inf:inf]>), ('SHIFT0', <Parameter 'SHIFT0', value=1797.8843857954282, bounds=[-inf:inf]>), ('WIDTH0', <Parameter 'WIDTH0', value=14.387609803061617, bounds=[0:inf]>), ('AMPLITUDE1', <Parameter 'AMPLITUDE1', value=2.0771486130830774, bounds=[-inf:inf]>), …
```
=> Mask out bad values using np.ma instead of just changing them

pyspeckit/cubes/cubes.py
The aperture extraction approach was horrendously memory inefficient before, making unnecessary whole copies of the cube.
=> Make aperture extraction on cubes memory efficient

pyspeckit/spectrum/fitters.py, pyspeckit/spectrum/models/model.py, pyspeckit/spectrum/models/polynomial_continuum.py, pyspeckit/spectrum/models/template.py, pyspeckit/spectrum/models/tests/test_template.py, pyspeckit/spectrum/plotters.py, pyspeckit/spectrum/tests/test_eqw.py
#389 dropped properties in a way that didn't make sense.  Instead, we just need to enforce that all xarrs are SpectroscopicAxis's
=> Bugfixes: revert 389, etc.

pyspeckit/cubes/SpectralCube.py
Fixed the bug where the x & y coordinates were passed into the `get_spectrum` method in the wrong (reversed) order when computing `_temp_moment`.
=> Corrected a xy order bug for the momenteach method

pyspeckit/parallel_map/parallel_map.py
Enable `paralel_map.run_tasks()` to remove extra dimensions from its output in the exception case. This should resolve issue https://github.com/pyspeckit/pyspeckit/issues/412.
=> Remove extra dimension from paralel_map's output
